### ISSUE TITLE
should have access to $HOME

### ISSUE THREAD

**Issue by 1player** [flathub/com.tonikelope.MegaBasterd#1]
by default this application downloads in $HOME, which isn't mounted in the flatpak, so all files are downloaded into its own filesystem and not easily reachable unless one knows what it's doing.

Please give this app access to $HOME so default settings work as intended. Alternatively, since `xdg-download` is mounted by default, configure the app so it downloads there by default.

**Comment by guihkx** [comment]
I agree that MegaBasterd should download stuff to `xdg-download` by default, but I disagree that we should give it read/write access to `$HOME` just because of this inconvenience.

And while it might sound easy to patch this just by setting the download location to `~/Downloads`, if we actually wanted to do this properly, we'd have to read the contents of `$XDG_CONFIG_HOME/user-dirs.dirs`, then parse the `XDG_DOWNLOAD_DIR` variable, since it might be on a different location for non-English speakers or users that manually changed it for whatever reason.

**Comment by muelli** [comment]
You can refer to xdg-download: https://docs.flatpak.org/en/latest/flatpak-command-reference.html

```
--filesystem=FS

    Allow the application access to a subset of the filesystem. This updates the [Context] group in the metadata. FS can be one of: home, host, host-os, host-etc, xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures, xdg-public-share, xdg-templates, xdg-videos, xdg-run, xdg-config, xdg-cache, xdg-data, an absolute path, or a homedir-relative path like ~/dir or paths relative to the xdg dirs, like xdg-download/subdir. The optional :ro suffix indicates that the location will be read-only. The optional :create suffix indicates that the location will be read-write and created if it doesn't exist. This option can be used multiple times. See the "[Context] filesystems" list in [flatpak-metadata(5)](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-metadata) for details of the meanings of these filesystems.
```

**Comment by guihkx** [comment]
I've sent a [patch](https://github.com/tonikelope/megabasterd/pull/464) to make MegaBasterd default to `xdg-download`, I'm currently waiting for a review.
